### ISSUE TITLE
It doesn't really work

### ISSUE THREAD

**Issue by Bircck** [aaronrudkin/exapunks_solitaire_bot#3]
been messing with it a bit even though I don't really know python. It doesn't seem to work and the biggest problem is that it mistakes the number "6" for "9". It's a shot in the dark whether or not you'll read this or care enough to fix it but I thought it would be worth a shot ^^

**Comment by robobenklein** [comment]
If you're using a different resolution monitor you'll need to redo the template images it looks for in card_back, ex: https://github.com/aaronrudkin/exapunks_solitaire_bot/commit/d38ef4af10bae38f5342f490458a3546eb99297b

**Comment by Bircck** [comment]
The problem is exactly that I'm not using a different resolution monitor, I'm using 1080, and there seems to be more than one things wrong. 

- first off is the stacks generated from the game (even a screenshot as argument) gives wrong stacks compared to what's expected from the exa_logic.py: 

exa_logic. py stack
#0 Type: stack: ['0R', 'CC', '8R', '8B']
#1 Type: stack: ['7R', '6B', '0B', 'DD']
#2 Type: stack: ['9B', 'SS', 'CC', '0R']
#3 Type: stack: ['DD', 'HH', 'HH', '0B']
#4 Type: stack: ['6R', 'HH', '6R', '9R']
#5 Type: stack: ['7B', '7R', 'SS', '9B']
#6 Type: stack: ['SS', 'HH', 'CC', '8R']
#7 Type: stack: ['6B', 'DD', '8B', '9R']
#8 Type: stack: ['CC', 'SS', 'DD', '7B']

exa_gui.py stack:
#0 Type: stack: ['ca', 'rd', 's\\', '8B', 'ca', 'rd', 's\\', '7R', 'ca', 'rd', 's\\', '9B', 'ca', 'rd', 's\\', '7B']
#1 Type: stack: ['ca', 'rd', 's\\', '0R', 'ca', 'rd', 's\\', '0R', 'ca', 'rd', 's\\', '7B', 'ca', 'rd', 's\\', 'CC']
#2 Type: stack: ['ca', 'rd', 's\\', '0B', 'ca', 'rd', 's\\', '7R', 'ca', 'rd', 's\\', 'HH', 'ca', 'rd', 's\\', 'HH']
#3 Type: stack: ['ca', 'rd', 's\\', '9R', 'ca', 'rd', 's\\', '8R', 'ca', 'rd', 's\\', '9B', 'ca', 'rd', 's\\', '8R']
#4 Type: stack: ['ca', 'rd', 's\\', 'DD', 'ca', 'rd', 's\\', '8B', 'ca', 'rd', 's\\', '9R', 'ca', 'rd', 's\\', '0B']
#5 Type: stack: ['ca', 'rd', 's\\', 'DD', 'ca', 'rd', 's\\', '9R', 'ca', 'rd', 's\\', 'DD', 'ca', 'rd', 's\\', 'CC']
#6 Type: stack: ['ca', 'rd', 's\\', 'SS', 'ca', 'rd', 's\\', 'SS', 'ca', 'rd', 's\\', 'HH', 'ca', 'rd', 's\\', 'CC']
#7 Type: stack: ['ca', 'rd', 's\\', 'SS', 'ca', 'rd', 's\\', 'CC', 'ca', 'rd', 's\\', 'DD', 'ca', 'rd', 's\\', '9R']
#8 Type: stack: ['ca', 'rd', 's\\', 'SS', 'ca', 'rd', 's\\', '9B', 'ca', 'rd', 's\\', 'HH', 'ca', 'rd', 's\\', '9B']
#9 Type: freecell: []

you can kinda fix this by adding the below code to on line 80 or around there. 
stack = [c[6:8] for c in stack]

- the requirements: file is obviously out of date here's the newst versions as of writing this
  mss==6.1.0
  numpy==1.19.4
  opencv-python==4.5.1.48
  Pillow==8.1.0
  PyAutoGUI==0.9.52
  six==1.15.0

- I also tested with the below code to see what image was scanned and there should be no problems there either in regards to the problem with resolution or something along those lines.

cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

- and then there is the thing with "6R/6B" registrering as "9R/9B" 

I'm not trying to blame you for something you've done for fun but I'm not able to get it to work and after some digging into the code and trying different configurations is it still not working. So that obviously leads me to the conclusion that something is wrong with the code in some sense and that's why I'm writing here.

**Comment by robobenklein** [comment]
If you have a 1080p monitor then this is NOT the same resolution, if you read the ReadMe you'll see it's run on a 2x DPI screen which is twice the number of pixels for the same content scale.

In my fork of the repo I've changed out all the images for 1x DPI 1080p and it works flawlessly.

**Comment by Bircck** [comment]
I didn't see it was a fork in your first comment, I simply figured it was some old commit that was referenced so I'm sorry about not seing that before. But even after downloading that fork you've made and trying to run it myself is it still not working. For reference I actually also asked another guy that made a solitaire solution for another zachtronics game "molek-syntez" earlier today and there definitely was a problem that had to be fixed which he then did and afterwards it worked. 

I'm very sorry for bothering and it's simply awesome that you've even responded to something that probably isn't what you'd prefer spending your time on and that quickly, and I really appreciate it. And in relation to the resolution I also had changed the "resolution_scale_click" from 0.5 to 1 and tested between them but with no real difference. I'm still not sure exactly what it is that's causing the problems, like if it has to do with dualmonitors, some specific version of some of the libraries screwing things over or something third. 

So to wrap it up, I just hoped the program could be fixed without being too big of a bother. Let me know if you're still keen on trying to sort something out, I just came to the conclusion when looking into the program and doing my trial and erroring that I hadn't fucked up and it's something with the program that's the problem. I still think that, but I'll gladly say I'm a dumbass if that has been the case all along, so yeah. happy new year and I hope to hear from you. :)

Link to the repo of the other solitaire i referenced: https://github.com/Hegemege/molek-syntez-solitaire-bot

**Comment by robobenklein** [comment]
Code in my fork is designed for a dual-monitor (or more) setup where it's fullscreened on a 1080p display.

Here's a video I did of it working and me running it in the terminal as I change some values: https://youtu.be/Yw08iDcl1uI

Not sure how much more help I can offer without actually sitting down at your computer, but I don't think it requires too much work to adapt it to different setups.

**Comment by Bircck** [comment]
It's great that you're able to get it to run on 1080p a year ago but it doesn't really change much for me. I've played around with and changed what could be changed but it doesn't alter anything I still get a fucked up stack and the program simply doesn't work. (the exec_gui.py obviously)

#0 Type: stack: ['10', '80', 'x1', '\\7', 'R1', '08', '0x', '1\\', 'HH', '10', '80', 'x1', '\\H', 'H1', '08', '0x', '1\\', 'HH']
#1 Type: stack: ['10', '80', 'x1', '\\7', 'R1', '08', '0x', '1\\', '7R', '10', '80', 'x1', '\\7', 'R1', '08', '0x', '1\\', '7R']
#2 Type: stack: ['10', '80', 'x1', '\\7', 'R1', '08', '0x', '1\\', 'HH', '10', '80', 'x1', '\\H', 'H1', '08', '0x', '1\\', 'HH']
#3 Type: stack: ['10', '80', 'x1', '\\7', 'R1', '08', '0x', '1\\', '6R', '10', '80', 'x1', '\\7', 'R1', '08', '0x', '1\\', '7R']
#4 Type: stack: ['10', '80', 'x1', '\\7', 'R1', '08', '0x', '1\\', '7R', '10', '80', 'x1', '\\7', 'R1', '08', '0x', '1\\', '7R']
#5 Type: stack: ['10', '80', 'x1', '\\7', 'R1', '08', '0x', '1\\', 'HH', '10', '80', 'x1', '\\7', 'R1', '08', '0x', '1\\', '0R']
#6 Type: stack: ['10', '80', 'x1', '\\S', 'S1', '08', '0x', '1\\', '7R', '10', '80', 'x1', '\\H', 'H1', '08', '0x', '1\\', '7R']
#7 Type: stack: ['10', '80', 'x1', '\\6', 'R1', '08', '0x', '1\\', '7R', '10', '80', 'x1', '\\S', 'S1', '08', '0x', '1\\', 'SS']
#8 Type: stack: ['10', '80', 'x1', '\\C', 'C1', '08', '0x', '1\\', 'CC', '10', '80', 'x1', '\\C', 'C1', '08', '0x', '1\\', 'CC']
#9 Type: freecell: []

So I think I'll just leave it at that and hopefully if someone else stumbles upon this in the future that they might have more luck than I did.

**Comment by pnemes** [comment]
for the stack issue see #12 
(card names from file names goes wrong on windows, because '\' is the directory separator, not '/')
